connection.test.exception=Cannot connect to [{0}]. Reason: [{1}]