connector.start.exception = Connector [{0}]Connector could not started successfully. Reason:[{1}]
